### ISSUE TITLE
centos6下执行报错

### ISSUE THREAD

**Issue by Jalright** [yumaojun03/dmidecode#5]
``` bash
SMBIOS 2.7.0 - table: address: 0xcf42c000, size: 4858
panic: runtime error: index out of range [36] with length 36

goroutine 1 [running]:
github.com/yumaojun03/dmidecode/parser/processor.ParseProcessor(0xc0002ca980, 0xc0002ca980, 0x2, 0xc00023b8a0)
	/data/apps/gopath/pkg/mod/github.com/yumaojun03/dmidecode@v0.1.3/parser/processor/parse.go:47 +0x8ef
github.com/yumaojun03/dmidecode.(*Decoder).Processor(0xc000222280, 0xc00021d904, 0x4, 0xc00021d904, 0x4, 0x4)
	/data/apps/gopath/pkg/mod/github.com/yumaojun03/dmidecode@v0.1.3/decoder.go:195 +0x115
```

**Comment by Jalright** [comment]
dmidecode输出信息
```bash
 dmidecode  -t memory
```
```bash
# dmidecode 2.12
SMBIOS 2.7 present.

Handle 0x1000, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 384 GB
	Error Information Handle: Not Provided
	Number Of Devices: 12

Handle 0x1100, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: 8192 MB
	Form Factor: DIMM
	Set: 1
	Locator: DIMM_A1 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous Registered (Buffered)
	Speed: 1600 MHz
	Manufacturer: 00CE00B300CE
	Serial Number: 1346C45D
	Asset Tag: 03132763
	Part Number: M393B1G70BH0-YK0  
	Rank: 1
	Configured Clock Speed: 1600 MHz

Handle 0x1101, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: 8192 MB
	Form Factor: DIMM
	Set: 1
	Locator: DIMM_A2 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous Registered (Buffered)
	Speed: 1600 MHz
	Manufacturer: 00CE00B300CE
	Serial Number: 1346C505
	Asset Tag: 03132763
	Part Number: M393B1G70BH0-YK0  
	Rank: 1
	Configured Clock Speed: 1600 MHz

Handle 0x1102, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: 8192 MB
	Form Factor: DIMM
	Set: 2
	Locator: DIMM_A3 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous Registered (Buffered)
	Speed: 1600 MHz
	Manufacturer: 00CE00B300CE
	Serial Number: 1346C454
	Asset Tag: 03132763
	Part Number: M393B1G70BH0-YK0  
	Rank: 1
	Configured Clock Speed: 1600 MHz

Handle 0x1103, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: 8192 MB
	Form Factor: DIMM
	Set: 2
	Locator: DIMM_A4 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous Registered (Buffered)
	Speed: 1600 MHz
	Manufacturer: 00CE00B300CE
	Serial Number: 1346C462
	Asset Tag: 03132763
	Part Number: M393B1G70BH0-YK0  
	Rank: 1
	Configured Clock Speed: 1600 MHz

Handle 0x1104, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 3
	Locator: DIMM_A5 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x1105, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 3
	Locator: DIMM_A6 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x1106, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 4
	Locator: DIMM_B1 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x1107, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 4
	Locator: DIMM_B2 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x1108, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 5
	Locator: DIMM_B3 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x1109, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 5
	Locator: DIMM_B4 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x110A, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 6
	Locator: DIMM_B5 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

Handle 0x110B, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: No Module Installed
	Form Factor: DIMM
	Set: 6
	Locator: DIMM_B6 
	Bank Locator: Not Specified
	Type: DDR3
	Type Detail: Synchronous
	Speed: Unknown
	Manufacturer:             
	Serial Number:         
	Asset Tag:         
	Part Number:                   
	Rank: Unknown
	Configured Clock Speed: Unknown

```
